version: "3"
services:
  proxy:
    image: rooknj/prysmalight-proxy:1.0.0
    container_name: proxy
    restart: always
    ports:
      - "80:80"
  web:
    depends_on:
      - proxy
    image: rooknj/prysmalight-web:latest
    container_name: web
    restart: always
  testWeb:
    depends_on:
      - proxy
    image: rooknj/prysmalight-web:test
    container_name: testWeb
    restart: always
  prysmalight:
    depends_on:
      - redis
      - mqtt
      - proxy
    image: rooknj/prysmalight:latest
    container_name: prysmalight
    restart: always
    environment:
      - DEBUG="main,config,service,db,pubsub,repo,server"
      - MQTT_HOST=mqtt
      - REDIS_HOST=redis      
  redis:
    image: rooknj/prysmalight-redis:1.0.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data
  mqtt:
    image: rooknj/prysmalight-mqtt:1.0.0
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - /mqtt/data
      - /mqtt/log
  homebridge:
    image: rooknj/prysmalight-homekit:1.0.0
    container_name: homekit
    restart: always
    network_mode: host
    volumes:
      - /homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
